### ISSUE TITLE
Set styles

### ISSUE THREAD

**Issue by hagenburger** [livingstyleguide/livingstyleguide#126]
As soon as [options are available](#123):

Set styles (style variables).

Old Yaml syntax (quotation marks needed):

```
style:
  base-font: 'Comic Sans MS, Arial, sans-serif'
  base-font-size: '7em'
  background-color: 'red'
  border-color: '$my-color'
  color: '#eee'
  code-color: 'darken(red, 10%)'
  color-swatch-border-radius: '0'
```

New command syntax (no quotation marks needed, normal CSS syntax applies):

```
@style base-font: 'Comic Sans MS', 'Arial', sans-serif
@style base-font-size: 7em
@style background-color: red
@style border-color: $my-color
@style color: #eee; code-color: darken(red, 10%); color-swatch-border-radius: 0
```
