### ISSUE TITLE
Allow to disable scoping of CSS

### ISSUE THREAD

**Issue by hagenburger** [livingstyleguide/livingstyleguide#155]
Sometimes it make sense to not scope the CSS. Especially for global styling of the style guide:

``` css
@css {
  .lsg--example {
    background: black;
  }
}
```

results in:

``` css
#current-section-id .lsg--example {
  background: black;
}
```

New:

``` css
@css scope: global {
  .lsg--example {
    background: black;
  }
}
```

should result in:

``` css
.lsg--example {
  background: black;
}
```

Same would apply when using `@sass` and `@scss`.
