### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by LookOnTheBrightSide** [livingstyleguide/livingstyleguide#197]
hi,
Thanks for the awesome gem! How do I remove the credits?
![screen shot 2016-06-11 at 12 38 13 pm](https://cloud.githubusercontent.com/assets/7965221/15984847/9ef75724-2fd1-11e6-8349-2f76d1add2f5.png)

**Comment by hagenburger** [comment]
For version 1.x I would suggest:

``` yaml
styleguide-scss: |
  .livingstyleguide--footer {
    display: none;
  }
```

In future versions I’m planning to have more flexibility.
