### ISSUE TITLE
Allow JavaScript Code in Configuration

### ISSUE THREAD

**Issue by hagenburger** [livingstyleguide/livingstyleguide#80]
Depending on if the line ends on “.js” or not, either `<script src="xyz.js"></script>` or `<script>someJavaScript()</script>` should be generated:

``` yaml
javascript-before:
  - 'modernizr.js'
  - 'alert("Hello World!")'
javascript-after:
  - 'http://code.jquery.com/jquery-2.0.3.js'
  - 'application.js'
  - 'alert("Goodbye World!")'
```

A real life example might be:

``` yaml
javascript-before:
  - '//use.typekit.net/abcd12efgh.js'
  - 'try{Typekit.load();}catch(e){}'
```
